# -*- coding: utf-8 -*-
"""get_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qlCTk5mUwJGbZ4T5qVPyhv6IEd10cqJ
"""

import os

os.environ['AWS_ACCESS_KEY_ID'] = 'KEY_ID'
os.environ['AWS_SECRET_ACCESS_KEY'] = 'KEY'
os.environ['AWS_DEFAULT_REGION'] = 'us-west-1'

!pip install boto3
!pip install s3fs

#aws SDK for python that enable direct API interaction with S3
import boto3
import pandas as pd

ratings = pd.read_csv(f's3://movielens-rec-bucket/raw/rating.csv')
movies = pd.read_csv(f's3://movielens-rec-bucket/raw/movie.csv')

print(ratings.head())
print(ratings[ratings['rating'] >= 4])

#preprocessing data
from scipy.sparse import csr_matrix

def convert_to_implicit(ratings, threshold: float = 4.0):
  '''
  convert explicit ratings to implicit feedback.
  Rating >= threshold becomes 1 interaction
  '''
  ratings['interaction'] = (ratings['rating'] >= threshold).astype(int)
  ratings = ratings[ratings['interaction'] > 0]
  return ratings

def encoding(ratings):
  '''
  encode userId and movieId
  return mappings and encoded data
  '''
  userId = {user: id for id, user in enumerate(ratings['userId'].unique())}
  itemId = {item: id for id, item in enumerate(ratings['movieId'].unique())}

  ratings['user_idx'] = ratings['userId'].map(userId)
  ratings['item_idx'] = ratings['movieId'].map(itemId)

  return ratings, userId, itemId

def sparse_matrix(ratings, n_users: int, n_items:int) -> csr_matrix:
  '''
  building a sparse matrix(user x item) for training the ALS implicit later
  '''
  interactions = csr_matrix(
      (ratings['interaction'], (ratings['user_idx'], ratings['item_idx'])),
      shape=(n_users, n_items)
  )

  return interactions

ratings_imp = convert_to_implicit(ratings)
print(ratings_imp.head())

ratings_encode, userId, itemId = encoding(ratings)
print(ratings_encode.head())

sparse_matrix = sparse_matrix(ratings_encode, len(userId), len(itemId))
print(sparse_matrix.shape)